# Generated by Django 3.2 on 2021-04-12 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20210412_0240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='transactions',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.transactions'),
        ),
    ]
